name: Scientific-visualisation
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asgiref=3.5.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cartopy=0.18.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - cftime=1.5.1.1
  - charset-normalizer=2.0.4
  - conda=22.9.0
  - conda-package-handling=1.9.0
  - cryptography=37.0.1
  - curl=7.84.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - django=4.1
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.11.0
  - geos=3.8.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - hdf4=4.2.13
  - hdf5=1.10.6
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzip=1.8.0
  - lz4-c=1.9.3
  - matplotlib-base=3.5.2
  - memory_profiler=0.58.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf4=1.5.7
  - nettle=3.7.3
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pillow=9.2.0
  - pip=22.1.2
  - proj=7.0.1
  - psutil=5.9.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - pytz=2022.1
  - readline=8.1.2
  - requests=2.28.1
  - ruamel_yaml=0.15.100
  - scipy=1.7.3
  - setuptools=63.4.1
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.39.2
  - sqlparse=0.4.1
  - tk=8.6.12
  - toolz=0.11.2
  - tqdm=4.64.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wheel=0.37.1
  - x264=1!157.20191217
  - xarray=0.20.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
